# -*- coding: utf-8 -*-
"""entregavel4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dWlws3s4voUhz1Wtaf7BJmvUugytBJz9
"""

import json
from pathlib import Path

ARQUIVO = Path("textos.json")


def carregar():

    if ARQUIVO.exists():
        return json.loads(ARQUIVO.read_text(encoding="utf-8"))
    return []


def salvar(textos):

    ARQUIVO.write_text(
        json.dumps(textos, ensure_ascii=False, indent=2), encoding="utf-8"
    )


def adicionar(textos):
    texto = input().strip()
    if texto:
        textos.append(texto)
        salvar(textos)
        print(f" {len(textos)}.")


def listar(textos):
    if not textos:
        print("Nenhum vento registrado.")
    for i, t in enumerate(textos, start=1):
        print(f"{i}. {t}")


def main():
    textos = carregar()
    menu = {"1": adicionar, "2": listar,}

    while True:
        print("(1)gendar consulta ou reunião  (2) Listar eventos agendados (0) fechar programa")
        opcao = input().strip()
        if opcao == "0":
            break
        acao = menu.get(opcao)
        if acao:
            acao(textos)
        else:
            print("Opção inválida.")


if __name__ == "__main__":
    main()